language: rust
sudo: false
dist: trusty # still in beta, but required for the prebuilt TF binaries

cache:
  cargo: true

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1
    - CC="gcc-4.9"
    - CXX="g++-4.9"
  matrix:
    - TF_RUST_BUILD_FROM_SRC=true
    - TF_RUST_BUILD_FROM_SRC=false


matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly


install:
  # Install dependencies only if we build tensorflow from source.
  - if [[ "$TF_RUST_BUILD_FROM_SRC" == "true" ]]; then source travis-ci/install.sh; fi
  - if [[ "$TF_RUST_BUILD_FROM_SRC" == "true" ]]; then pip install --user numpy; fi

script:
  - cargo test -vv -j 2 --features tensorflow_unstable
  - cargo run --example regression
  - cargo run --features tensorflow_unstable --example expressions
  - cargo doc -vv --features tensorflow_unstable
  - # TODO(#66): Re-enable: (cd tensorflow-sys && cargo test -vv -j 1)
  - (cd tensorflow-sys && cargo doc -vv)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.9
      - gcc-4.9
      - oracle-java8-installer
      - swig

notifications:
  email: false
